schema_version = "1.0.0"

# Unoffical Cats Blender Plugin Extenstion
id = "cats_blender_plugin"
version = "4.3.1"
name = "Unoffical Cats Blender Plugin"
tagline = "A tool designed to shorten steps needed to import and optimize models into VRChat"
maintainer = "Unoffical Cats Team <hello@yusarina.xyz>"
type = "add-on"
permissions = ["files", "network"]
website = "https://github.com/teamneoneko/Cats-Blender-Plugin-Unofficial-"
tags = ["3D View", "Modeling", "Mesh", "Object"]
blender_version_min = "4.3.0"
license = [
  "SPDX:MIT",
]
